[build]
  command = "npm run netlify-build"
  publish = "client/dist"

[functions]
  node_bundler = "webpack"
  environment = {
    MONGODB_URI = "${MONGODB_URI}",
    JWT_SECRET = "${JWT_SECRET}"
  }

[functions.api]
  memory_size = 1024
  timeout = 10
  environment = {
    MONGODB_URI = "${MONGODB_URI}",
    JWT_SECRET = "${JWT_SECRET}"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  MONGODB_URI = "${MONGODB_URI}"
  JWT_SECRET = "${JWT_SECRET}"
